version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.12  
    steps:
      - checkout
      - run:
          name: Install  All dependencies
          command: |
            python -m pip install --upgrade pip
      - run:
          name: Run index.py
          command: |
            pipenv run python api/index.py 

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
